apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-db
spec:
  selector:
    matchLabels:
      appdb: web-app-db
  replicas: 1
  template:
    metadata:
      labels:
        appdb: web-app-db
    spec:
      containers:
      - name: web-app-db
        image: mongo:3.3
        env:
        - name: MONGODB_DATABASE
          value: testdata
        ports:
        - containerPort: 27017

