apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8001
      protocol: TCP
      targetPort: 8001
      nodePort: 32007

