{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.containerport }}
      targetPort: {{ .Values.ports.containerport }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.port }}
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
{{- end }}